app/Http/Controllers/Admin/BrandController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entities\Brand;
use App\Entities\BrandIlProjectBrand;
use App\Entities\BrandPhoto;
use App\Entities\BrandUser;
use App\Entities\User;
use App\Http\Controllers\Controller;
use App\Http\Repositories\SyncRepository;
use Illuminate\Cache\Repository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;

class BrandController extends Controller
{
    public function __construct()
    {

    }

    public function create()
    {

        $title = new \stdClass();
        $title->icon = "fa fa-shield";
        $title->title = "Marchi";
        $title->description = "Nuova";

        $breadcumbs = [
            (object)array('title' => 'Home', 'url' => route('brand.dashboard')),
            (object)array('title' => 'Nuovo', 'url' => null)
        ];

        $menu = new \stdClass();
        $menu->area = "marchi";
        $menu->option = "create";

        $ilprojectBrands = DB::connection("mysql_ilproject")
            ->table("marchi")
            ->orderBy("nome")
            ->get();

        $users = User::where("is_superadmin", 0)->get();

        return view('admin.brands.create', [
            'title' => $title,
            'breadcumbs' => $breadcumbs,
            'menu' => $menu,
            'ilprojectBrands' => $ilprojectBrands,
            'users' => $users
        ]);
    }

    public function store(Request $request)
    {
        $fields = [
            'name' => [
                'required',
                Rule::unique('brands')
            ],
            'name_public' => 'required',
            'url_video' => 'nullable|url'
        ];

        $this->validate($request, $fields);

        $marchio = new Brand();
        $marchio->name = $request->name;
        $marchio->name_public = $request->name_public;
        $marchio->url_video = $request->url_video;
        $marchio->text = $request->text;
        $marchio->warranty_extension = empty($request->warranty_extension) ? 0 : $request->warranty_extension;
        $marchio->discount_percentage = $request->discount_percentage;
        $marchio->discount_amount = $request->discount_amount;
        $marchio->survey_option = empty($request->survey_option) ? 0 : $request->survey_option;
        $marchio->survey_branch_option = empty($request->survey_branch_option) ? 0 : $request->survey_branch_option;
        $marchio->survey_item_option = empty($request->survey_item_option) ? 0 : $request->survey_item_option;
        $marchio->stats_option = empty($request->stats_option) ? 0 : $request->stats_option;
        $marchio->discount_option = empty($request->discount_option) ? 0 : $request->discount_option;
        $marchio->warranty_option = empty($request->warranty_option) ? 0 : $request->warranty_option;
	    $marchio->shop_url = $request->shop_url;
	    $marchio->shop_api_key = $request->shop_api_key;
	    $marchio->shop_type = $request->shop_type;
		$marchio->header_css = $request->header_css;
		
        $marchio->save();

        foreach ($request->ilprojectBrands as $ilprojectBrand) {
            $obj = new BrandIlProjectBrand();
            $obj->brand_id = $marchio->id;
            $obj->ilproject_brand_id = $ilprojectBrand;
            $obj->save();
        }

        BrandUser::where("brand_id", $marchio->id)->delete();
        foreach ($request->users as $user) {
            $obj = new BrandUser();
            $obj->brand_id = $marchio->id;
            $obj->user_id = $user;
            $obj->save();
        }

        if ($request->logo != null)
        {
            $logo = $request->logo;
            $hash = $logo->hashName();
            $folder = substr($hash, 0, 2);
            $dir = 'brands' . DIRECTORY_SEPARATOR . $folder;
            $path = $logo->storeAs($dir, $hash, 'public');
            $marchio->logo = $path;
            $marchio->save();
        }

        return redirect()->route('admin.brands.edit', $marchio->id);
    }

    public function index(Request $request)
    {
        $user = $request->user();

        $title = new \stdClass();
        $title->icon = "fa fa-shield";
        $title->title = "Marchi";
        $title->description = "Elenco";

        $breadcumbs = [
            (object)array('title' => 'Home', 'url' => route('brand.dashboard')),
            (object)array('title' => 'Elenco', 'url' => null)
        ];

        $menu = new \stdClass();
        $menu->area = "marchi";
        $menu->option = "elenco";

        $brands = Brand::with("photo", "users")
            ->get();

        $brands->load(['photo' => function ($query) {
            $query->orderBy('position', 'asc');
        }]);

        return view('admin.brands.index', ['brands' => $brands, 'title' => $title, 'breadcumbs' => $breadcumbs, 'menu' => $menu]);
    }

    public function edit(Request $request, Brand $brand)
    {
        $brand->load(['photo' => function ($query) {
                $query->orderBy('position', 'asc');
            }])
            ->with(["ilprojectBrands", "brands"]);

        $user = $request->user();

        $title = new \stdClass();
        $title->icon = "fa fa-shield";
        $title->title = "Marchi";
        $title->description = "Modifica";

        $breadcumbs = [
            (object)array('title' => 'Home', 'url' => route('brand.dashboard')),
            (object)array('title' => 'Elenco', 'url' => route('brand.brands.index')),
            (object)array('title' => 'Modifica', 'url' => null)
        ];

        $menu = new \stdClass();
        $menu->area = "marchi";
        $menu->option = "elenco";

        $ilprojectBrands = DB::connection("mysql_ilproject")
            ->table("marchi")
            ->orderBy("nome")
            ->get();

        $users = User::where("is_superadmin", 0)->get();

        return view('admin.brands.edit', [
            'brand' => $brand,
            'title' => $title,
            'breadcumbs' => $breadcumbs,
            'menu' => $menu,
            'ilprojectBrands' => $ilprojectBrands,
            'users' => $users
        ]);
    }

    public function update(Request $request, Brand $brand)
    {

        $brand->load('photo');
        $user = $request->user();

        $lastPosition = count($brand->photo);

        $fields = [
            'name' => [
                'required',
                Rule::unique('brands')->ignore($brand->id)
            ],
            'name_public' => 'required',
            'url_video' => 'nullable|url',
            'warranty_extension' => 'numeric',
            'discount_validity' => 'numeric'
        ];

        if (is_array($request->file)) {
            $nbr = count($request->file) - 1;
            foreach (range(0, $nbr) as $index) {
                $fields['file.' . $index] = 'file|mimes:jpeg,bmp,png|max:256';
            }
        }

        $this->validate($request, $fields);

        $brand->name = $request->name;
        $brand->name_public = $request->name_public;
        $brand->url_video = $request->url_video;
        $brand->text = $request->text;
        $brand->warranty_extension = $request->warranty_extension;
        $brand->discount_percentage = $request->discount_percentage;
        $brand->discount_amount = $request->discount_amount;
        $brand->discount_validity = $request->discount_validity;
        $brand->search_option = $request->search_option;
        $brand->survey_option = empty($request->survey_option) ? 0 : $request->survey_option;
        $brand->survey_branch_option = empty($request->survey_branch_option) ? 0 : $request->survey_branch_option;
        $brand->survey_item_option = empty($request->survey_item_option) ? 0 : $request->survey_item_option;
        $brand->stats_option = empty($request->stats_option) ? 0 : $request->stats_option;
        $brand->discount_option = empty($request->discount_option) ? 0 : $request->discount_option;
        $brand->warranty_option = empty($request->warranty_option) ? 0 : $request->warranty_option;
	    $brand->shop_url = $request->shop_url;
	    $brand->shop_api_key = $request->shop_api_key;
	    $brand->shop_type = $request->shop_type;
	    $brand->header_css = $request->header_css;

        $brand->save();

        BrandIlProjectBrand::where("brand_id", $brand->id)->delete();
        foreach ($request->ilprojectBrands as $ilprojectBrand) {
            $obj = new BrandIlProjectBrand();
            $obj->brand_id = $brand->id;
            $obj->ilproject_brand_id = $ilprojectBrand;
            $obj->save();
        }

        BrandUser::where("brand_id", $brand->id)->delete();
        foreach ($request->users as $user) {
            $obj = new BrandUser();
            $obj->brand_id = $brand->id;
            $obj->user_id = $user;
            $obj->save();
        }

        if ($request->logo != null)
        {
            $logo = $request->logo;
            $hash = $logo->hashName();
            $folder = substr($hash, 0, 2);
            $dir = 'brands' . DIRECTORY_SEPARATOR . $folder;
            $path = $logo->storeAs($dir, $hash, 'public');
            $brand->logo = $path;
            $brand->save();
        }

        if (is_array($request->file)) {
            foreach ($request->file as $key => $photo) {
                $hash = $photo->hashName();
                $folder = substr($hash, 0, 2);
                $dir = 'brands' . DIRECTORY_SEPARATOR . $folder;
                $path = $photo->storeAs($dir, $hash, 'public');

                BrandPhoto::updateOrCreate([
                    'stored' => $path,
                    'brand_id' => $brand->id
                ], [
                    'original' => $photo->getClientOriginalName(),
                    'mime' => $photo->getMimeType(),
                    'position' => $key + $lastPosition
                ]);
            }
        }

        if (is_array($request->gallery)) {
            foreach ($request->gallery as $key => $gallery_id) {

app/Http/Controllers/Brand/Account/PasswordController.php
<?php

namespace App\Http\Controllers\Brand\Account;

use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class PasswordController extends Controller
{

    public function edit(Request $request)
    {
        $menu = new \stdClass();

        $title = new \stdClass();
        $title->icon = "fa fa-key";
        $title->title = "Password";
        $title->description = "Modifica della password di accesso";

        $breadcumbs = [
            (object)array('title' => 'Home', 'url' => route('brand.dashboard')),
            (object)array('title' => 'Password', 'url' => null)
        ];

        $menu = new \stdClass();
        $menu->area = "dashboard";
        $menu->option = "";

        return view('brand.account.password')
            ->with([
                'title' => $title,
                'breadcumbs' => $breadcumbs,
                'menu' => $menu
            ]);
    }

    public function update(Request $request)
    {
        $user = $request->user();

        $fields = [
            'current_password' => 'current_password',
            'password' => 'required|confirmed'
        ];

        $this->validate($request, $fields);

        $user->password = bcrypt($request->password);
        $user->save();

        return redirect()->route('brand.dashboard');
    }
}

app/Http/Controllers/Brand/BranchController.php
<?php
namespace App\Http\Controllers\Brand;

use App\Entities\Branch;
use App\Entities\Brand;
use App\Entities\Item;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class BranchController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = $request->user();

        $title = new \stdClass();
        $title->icon = "fa fa-code-fork";
        $title->title = "Segmenti";
        $title->description = "Elenco";

        $breadcumbs = [
            (object)array('title' => 'Home', 'url' => route('brand.dashboard')),
            (object)array('title' => 'Elenco', 'url' => null),
        ];

        $menu = new \stdClass();
        $menu->area = "segmenti";
        $menu->option = "elenco";

        $branches = Branch::whereBrandIn($user->brands->pluck('id')->toArray())
            ->withCount('items')
            ->withCount('surveys')
            ->withCount('datasheets')
            ->get();

        $branches->load('brand','items');

        return view('brand.branches.index')
            ->with([
                'title' => $title,
                'breadcumbs' => $breadcumbs,
                'menu' => $menu,
                'branches' => $branches
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $user = $request->user();

        $title = new \stdClass();
        $title->icon = "fa fa-code-fork";
        $title->title = "Segmenti";
        $title->description = "Nuovo";

        $breadcumbs = [
            (object)array('title' => 'Home', 'url' => route('brand.dashboard')),
            (object)array('title' => 'Segmenti', 'url' => route('brand.branches.index')),
            (object)array('title' => 'Nuovo', 'url' => null),
        ];

        $menu = new \stdClass();
        $menu->area = "segmenti";
        $menu->option = "create";

        $brands = Brand::whereBrandIn($user->brands->pluck('id')->toArray())->orderBy('name')->get();

        return view('brand.branches.create')
            ->with([
                'title' => $title,
                'breadcumbs' => $breadcumbs,
                'menu' => $menu,
                'brands' => $brands
            ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $fields = [
            'brand_id' => 'required',
            'name' => [
                'required',
                Rule::unique('branches')->where(function($query) use ($request){
                    $query->where('brand_id', $request->brand_id);
                })
            ]
        ];

        $this->validate($request, $fields);

        $branch = new Branch;
        $branch->brand_id = $request->brand_id;
        $branch->name = $request->name;
        $branch->text = empty($request->text) ? null : $request->text;
        $branch->save();

        return redirect()->route('brand.branches.edit', $branch->id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Branch $branch)
    {
        $this->authorize('update', $branch);

        $branch->load('brand');

        $user = $request->user();

        $title = new \stdClass();
        $title->icon = "fa fa-code-fork";
        $title->title = "Segmenti";
        $title->description = "Modifica";

        $breadcumbs = [
            (object)array('title' => 'Home', 'url' => route('brand.dashboard')),
            (object)array('title' => 'Segmenti', 'url' => route('brand.branches.index')),
            (object)array('title' => 'Modifica', 'url' => null)
        ];

        $menu = new \stdClass();
        $menu->area = "segmenti";
        $menu->option = "elenco";

        $items = Item::where('brand_id', $branch->brand_id)->get();

        return view('brand.branches.edit')
            ->with([
                'title' => $title,
                'breadcumbs' => $breadcumbs,
                'menu' => $menu,
                'branch' => $branch,
                'items' => $items
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Branch $branch)
    {
        $this->authorize('update', $branch);

        $fields = [
            'name' => [
                'required',
                Rule::unique('branches')->where(function($query) use ($request){
                    $query->where('brand_id', $request->brand_id);
                })->ignore($branch->id)
            ]
        ];

        $this->validate($request, $fields);

        $branch->name = $request->name;
        $branch->text = empty($request->text) ? null : $request->text;
        $branch->items()->sync(json_decode($request->datatable));
        $branch->save();

        return redirect()->route('brand.branches.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Branch $branch)
    {
        $this->authorize('delete', $branch);

        if($branch->surveys->count() == 0 && $branch->datasheets->count() == 0)
        {
            $branch->items()->detach();
            $branch->delete();
        }

        return back();
    }
}

resources/views/brand/branches/create.blade.php
@extends('brand.layout.app')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
            	<h4 class="panel-title">Nuovo segmento</h4>
            </div>

            <div class="panel-body">
				<form class="form-horizontal" action="{{ route('brand.branches.store') }}" method="POST">
					{{ csrf_field() }}
					<div class="form-group">
						<label class="col-sm-3 control-label" for="brand_id">Marchio <span class="asterisk">*</span></label>
						<div class="col-sm-6">
							<select class="form-control" name="brand_id" id="brand_id" required>
							<option value="">-- seleziona --</option>
							@foreach($brands as $brand)
								@if( old('brand_id') == $brand->id )
									<option value="{{ $brand->id }}" selected>{{ $brand->name }}</option>
								@else
									<option value="{{ $brand->id }}">{{ $brand->name }}</option>
								@endif
							@endforeach
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="name">Nome <span class="asterisk">*</span></label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="name" id="name" value="{{ old('name') }}" required />
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="text">Descrizione</label>
						<div class="col-sm-6">
							<textarea class="form-control" rows="5" name="text" id="text">{{ old('text') }}</textarea>
							<span class="help-block">Informazioni aggiuntive per il segmento</span>
						</div>
					</div>

					@if (count($errors) > 0)
					<div class="form-group">
						<div class="col-sm-6 col-sm-offset-3">
							<div class="alert alert-danger">
								<ul>
									@foreach ($errors->all() as $error)
										<li>{{ $error }}</li>
									@endforeach
								</ul>
							</div>
						</div>
					</div>
					@endif
					<div class="form-group">
						<div class="col-sm-6 col-sm-offset-3">
							<button class="btn btn-primary">Crea</button>
						</div>
					</div>
				</form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/brand/branches/edit.blade.php
@extends('brand.layout.app')

@section('content')

<form class="form-horizontal" name="form" id="form" action="{{ route('brand.branches.update', $branch->id) }}" method="POST" enctype="multipart/form-data">
{{ csrf_field() }}
{{ method_field('PUT') }}
<input type="hidden" name="datatable" value="" />

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
            	<h4 class="panel-title">Modifica segmento</h4>
            </div>

            <div class="panel-body">
            	<div class="form-group">
					<label class="col-sm-3 control-label" for="brand_id">Marchio</label>
					<div class="col-sm-6">
						<p class="form-control-static">{{ $branch->brand->name }}</p>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-3 control-label" for="name">Nome <span class="asterisk">*</span></label>
					<div class="col-sm-6">
						<input type="text" class="form-control" name="name" id="name" value="{{ $branch->name }}" required />
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-3 control-label" for="text">Descrizione</label>
					<div class="col-sm-6">
						<textarea class="form-control" rows="5" name="text" id="text">{{ $branch->text }}</textarea>
					</div>
				</div>
				@if (count($errors) > 0)
				<div class="form-group">
					<div class="col-sm-6 col-sm-offset-3">
						<div class="alert alert-danger">
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div>
					</div>
				</div>
				@endif
				<div class="form-group">
					<div class="col-sm-6 col-sm-offset-3">
						<button class="btn btn-primary">Modifica</button>
					</div>
				</div>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="panel panel-default">

        	<div class="panel-heading">
        		<h4 class="panel-title">Elenco articoli</h4>
        		<p>Selezionare gli articoli da includere nel segmento</p>
        	</div>

            <div class="panel-body">
				<div class="table-responsive">
					<table class="table" id="table1" width="100%">
						<thead>
							<tr>
								<th>Barcode</th>
								<th>Codice</th>
								<th>Descrizione</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
						@foreach ($items as $item)
							<tr>
								<td>{{ $item->barcode }}</td>
								<td>{{ $item->name }}</td>
								<td>{{ $item->text }}</td>
								<td class="table-action">
									@if( $branch->items->contains($item->id))
										<input type="checkbox" value="{{ $item->id }}" checked>
									@else
										<input type="checkbox" value="{{ $item->id }}">
									@endif
								</td>
							</tr>
						@endforeach
						</tbody>
					</table>
				</div><!-- table-responsive -->
            </div>
        </div>
    </div>
</div>

</form>

@endsection

@section('javascript')
<script type="text/javascript">
$.fn.dataTable.ext.order['dom-checkbox'] = function  ( settings, col )
{
    return this.api().column( col, {order:'index'} ).nodes().map( function ( td, i ) {
        return $('input', td).prop('checked') ? '1' : '0';
    } );
}


var t = $('#table1').DataTable({
	columnDefs: [
		{
			"orderable": false, "targets": 0
		},
		{
			"orderDataType": "dom-checkbox",
			"targets": 3
		},
		{
			"targets": 2,
			"data": '',
			"render": function ( data, type, full, meta ) {
				return type === 'display' && data.length > 40 ? '<span title="'+data+'">'+data.substr( 0, 38 )+'...</span>' : data;
			}
		},
	],
	order: [
		[3, "desc"]
	]
});

$('#form').submit(function(e){
	var matches = [];
	var checkedcollection = t.$("input:checked", { "page": "all" });
		checkedcollection.each(function (index, elem) {
		matches.push($(elem).val());
	});

	document.form.datatable.value = JSON.stringify(matches);
});

</script>
@endsection

resources/views/brand/branches/index.blade.php
@extends('brand.layout.app')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
				<div class="table-responsive">
					<table class="table" id="table1">
						<thead>
							<tr>
								<th>Nome</th>
								<th>Marchio</th>
								<th>Articoli</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
						@foreach ($branches as $branch)
							<tr>
								<td>{{ $branch->name }}</td>
								<td>{{ $branch->brand->name }}</td>
								<td>{{ $branch->items_count }}</td>
								<td class="table-action">
									<div class="btn-group">
										<button class="btn btn-xs btn-default" type="button" onClick="return document.location.href = '{{ route('brand.branches.edit', $branch->id) }}';">Modifica</button>

										@if($branch->surveys_count == 0 && $branch->datasheets_count == 0)
										<button class="btn btn-xs btn-default dropdown-toggle" type="button" data-toggle="dropdown">
											<span class="caret"></span>
											<span class="sr-only">Toggle Dropdown</span>
										</button>
										<ul class="dropdown-menu" role="menu">
											<li><a href="#" class="btn-delete" data-branch-id="{{ $branch->id }}">Elimina</a></li>
										</ul>
										@endif
									</div>
								</td>
							</tr>
						@endforeach
						</tbody>
					</table>
				</div><!-- table-responsive -->
            </div>
        </div>
    </div>
</div>


<div class="modal fade modal-delete" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="deleteItem" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Confermi la cancellazione?</h4>
        </div>
        <div class="modal-body">
        	<p>
        		Nome: <span id="lbl-delete-name"></span><br />
        		Marchio: <span id="lbl-delete-brand"></span><br />
        	</p>
        </div>
        <div class="modal-footer">
        	<form method="post" action="" name="form_branch_delete">
        		{{ csrf_field() }}
        		{{ method_field('DELETE') }}

        		<input type="hidden" name="branch_id" value="" />

	        	<button aria-hidden="true" data-dismiss="modal" class="btn btn-default" type="button">Annulla</button>
	        	<button class="btn btn-danger" type="submit">Elimina</button>
	        </form>
        </div>
    </div>
  </div>
</div>

<script>
jQuery(document).ready(function() {
    "use strict";

    $("#table1").on('click','.btn-delete', function(){
		var array = t.row($(this).parents('tr')).data();

		document.getElementById('lbl-delete-name').innerText = array[0];
		document.getElementById('lbl-delete-brand').innerText = array[1];

		form_branch_delete.action = '/branches/' + $(this).data("branch-id");
		form_branch_delete.branch_id.value = $(this).data("branch-id");

		$('.modal-delete').modal('show');
	});

	$('.modal-delete').on('hidden.bs.modal', function (e) {
		document.getElementById('lbl-delete-name').innerText = "";
		document.getElementById('lbl-delete-brand').innerText = "";

		form_branch_delete.action = '';
		form_branch_delete.branch_id.value = 0;
	});
});
</script>

@endsection